formatting:
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
  NoWildcardImports:
    active: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 120
  TrailingWhitespace:
    active: true

exceptions:
  TooGenericExceptionThrown:
    active: false
  TooGenericExceptionCaught:
    active: false

performance:
  SpreadOperator:
    active: false